# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ye1HD8XDW02CQ5T129hJC3X17LuXnnL9
"""

def power(a, n):
    # Базовый случай: если степень равна 0, результат всегда 1
    if n == 0:
        return 1
    # Рекурсивный случай: a^n = a * a^(n-1)
    return a * power(a, n - 1)

# Пример использования функции
a = 2.5
n = 3
result = power(a, n)
print(f"{a} в степени {n} равно {result}")